on:
  workflow_dispatch:
  push:
    branches:
      - contributors-action

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    name: Atualiza CONTRIBUTORS
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/okfn-contributors
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'CONTRIBUTORS.md .all-contributorsrc'
          push: true
          message: 'atualiza lista de pessoas contribuidoras'

